/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ApplySlugRouteImport } from './routes/apply.$slug'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppVacanciesIndexRouteImport } from './routes/app.vacancies.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppVacanciesNewRouteImport } from './routes/app.vacancies.new'
import { Route as AppVacanciesVacancyIdRouteImport } from './routes/app.vacancies.$vacancyId'
import { Route as AppCandidatesIdRouteImport } from './routes/app.candidates.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminPaymentsRouteImport } from './routes/app.admin.payments'
import { Route as AppAdminOrgsRouteImport } from './routes/app.admin.orgs'
import { Route as ApiPublicApplyRouteImport } from './routes/api.public.apply'
import { Route as ApiPublicAnalyzeRouteImport } from './routes/api.public.analyze'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api.public.mp.webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApplySlugRoute = ApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVacanciesIndexRoute = AppVacanciesIndexRouteImport.update({
  id: '/vacancies/',
  path: '/vacancies/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppVacanciesNewRoute = AppVacanciesNewRouteImport.update({
  id: '/vacancies/new',
  path: '/vacancies/new',
  getParentRoute: () => AppRoute,
} as any)
const AppVacanciesVacancyIdRoute = AppVacanciesVacancyIdRouteImport.update({
  id: '/vacancies/$vacancyId',
  path: '/vacancies/$vacancyId',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesIdRoute = AppCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrgsRoute = AppAdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicApplyRoute = ApiPublicApplyRouteImport.update({
  id: '/api/public/apply',
  path: '/api/public/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyzeRoute = ApiPublicAnalyzeRouteImport.update({
  id: '/api/public/analyze',
  path: '/api/public/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp/webhook',
  path: '/api/public/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/app/admin/orgs': typeof AppAdminOrgsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/vacancies/$vacancyId': typeof AppVacanciesVacancyIdRoute
  '/app/vacancies/new': typeof AppVacanciesNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/vacancies/': typeof AppVacanciesIndexRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/app': typeof AppIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/app/admin/orgs': typeof AppAdminOrgsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/vacancies/$vacancyId': typeof AppVacanciesVacancyIdRoute
  '/app/vacancies/new': typeof AppVacanciesNewRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/vacancies': typeof AppVacanciesIndexRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/apply/$slug': typeof ApplySlugRoute
  '/app/': typeof AppIndexRoute
  '/api/public/analyze': typeof ApiPublicAnalyzeRoute
  '/api/public/apply': typeof ApiPublicApplyRoute
  '/app/admin/orgs': typeof AppAdminOrgsRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/candidates/$id': typeof AppCandidatesIdRoute
  '/app/vacancies/$vacancyId': typeof AppVacanciesVacancyIdRoute
  '/app/vacancies/new': typeof AppVacanciesNewRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/vacancies/': typeof AppVacanciesIndexRoute
  '/api/public/mp/webhook': typeof ApiPublicMpWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/subscription'
    | '/apply/$slug'
    | '/app/'
    | '/api/public/analyze'
    | '/api/public/apply'
    | '/app/admin/orgs'
    | '/app/admin/payments'
    | '/app/admin/users'
    | '/app/candidates/$id'
    | '/app/vacancies/$vacancyId'
    | '/app/vacancies/new'
    | '/app/admin/'
    | '/app/vacancies/'
    | '/api/public/mp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/subscription'
    | '/apply/$slug'
    | '/app'
    | '/api/public/analyze'
    | '/api/public/apply'
    | '/app/admin/orgs'
    | '/app/admin/payments'
    | '/app/admin/users'
    | '/app/candidates/$id'
    | '/app/vacancies/$vacancyId'
    | '/app/vacancies/new'
    | '/app/admin'
    | '/app/vacancies'
    | '/api/public/mp/webhook'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/dashboard'
    | '/app/settings'
    | '/app/subscription'
    | '/apply/$slug'
    | '/app/'
    | '/api/public/analyze'
    | '/api/public/apply'
    | '/app/admin/orgs'
    | '/app/admin/payments'
    | '/app/admin/users'
    | '/app/candidates/$id'
    | '/app/vacancies/$vacancyId'
    | '/app/vacancies/new'
    | '/app/admin/'
    | '/app/vacancies/'
    | '/api/public/mp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApplySlugRoute: typeof ApplySlugRoute
  ApiPublicAnalyzeRoute: typeof ApiPublicAnalyzeRoute
  ApiPublicApplyRoute: typeof ApiPublicApplyRoute
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/apply/$slug': {
      id: '/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/apply/$slug'
      preLoaderRoute: typeof ApplySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacancies/': {
      id: '/app/vacancies/'
      path: '/vacancies'
      fullPath: '/app/vacancies/'
      preLoaderRoute: typeof AppVacanciesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/vacancies/new': {
      id: '/app/vacancies/new'
      path: '/vacancies/new'
      fullPath: '/app/vacancies/new'
      preLoaderRoute: typeof AppVacanciesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vacancies/$vacancyId': {
      id: '/app/vacancies/$vacancyId'
      path: '/vacancies/$vacancyId'
      fullPath: '/app/vacancies/$vacancyId'
      preLoaderRoute: typeof AppVacanciesVacancyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates/$id': {
      id: '/app/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/app/candidates/$id'
      preLoaderRoute: typeof AppCandidatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/payments': {
      id: '/app/admin/payments'
      path: '/payments'
      fullPath: '/app/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/orgs': {
      id: '/app/admin/orgs'
      path: '/orgs'
      fullPath: '/app/admin/orgs'
      preLoaderRoute: typeof AppAdminOrgsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/apply': {
      id: '/api/public/apply'
      path: '/api/public/apply'
      fullPath: '/api/public/apply'
      preLoaderRoute: typeof ApiPublicApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analyze': {
      id: '/api/public/analyze'
      path: '/api/public/analyze'
      fullPath: '/api/public/analyze'
      preLoaderRoute: typeof ApiPublicAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mp/webhook': {
      id: '/api/public/mp/webhook'
      path: '/api/public/mp/webhook'
      fullPath: '/api/public/mp/webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminOrgsRoute: typeof AppAdminOrgsRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminOrgsRoute: AppAdminOrgsRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCandidatesIdRoute: typeof AppCandidatesIdRoute
  AppVacanciesVacancyIdRoute: typeof AppVacanciesVacancyIdRoute
  AppVacanciesNewRoute: typeof AppVacanciesNewRoute
  AppVacanciesIndexRoute: typeof AppVacanciesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppIndexRoute: AppIndexRoute,
  AppCandidatesIdRoute: AppCandidatesIdRoute,
  AppVacanciesVacancyIdRoute: AppVacanciesVacancyIdRoute,
  AppVacanciesNewRoute: AppVacanciesNewRoute,
  AppVacanciesIndexRoute: AppVacanciesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApplySlugRoute: ApplySlugRoute,
  ApiPublicAnalyzeRoute: ApiPublicAnalyzeRoute,
  ApiPublicApplyRoute: ApiPublicApplyRoute,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
